### ISSUE TITLE
Missing required parameters: sitekey

### ISSUE THREAD

**Issue by sandonet13** [pbiering/roundcube-rcguard#1]
I got this error in browser console, do you have any idea why ?
i already put my site key in the config.

**Comment by GSEPE** [comment]
check that your **config.inc.php** file in the **plugins/rcguard** folder looks like this:
```
 
/ CAPTCHA site key
$config['recaptcha_publickey'] = 'xxxxxxxxxxxxxxxxxxxx';

// CAPTCHA secret key
$config['recaptcha_privatekey'] = 'xxxxxxxxxxxxxxx-xxxxxxxxxxx';
```

Probably, you have changed the $config['**recaptcha_publickey**'] value, or there is some typo in the string.

**Comment by pbiering** [comment]
assumed issue was on layer 8 and is closed locally already.
