### ISSUE TITLE
Cloudflare Turnstile not showing on logon page with Roundcube Webmail 1.6.7 and rcguard 1.4.0

### ISSUE THREAD

**Issue by roylaprattep** [pbiering/roundcube-rcguard#5]
Hi,

Here is the informations of my issues,

Cloudflare Turnstile not showing on logon page with Roundcube Webmail 1.6.7 and rcguard 1.4.0.

It's there, but not showing in Edge, Chrome, Firefox... Tried many browsers. I need to disable the rcguard plugin to be able to login because the turnstile is not showing. It's "working", but it's invisible... When I try to login, I see "Captcha needed....", but as explained, there is no box shown.

Google reCaptcha is working fine tho. But the layout is not that beautiful, it's not very aesthetic. Is there a way to align everything correctly? The reCaptcha is on top the "Login" button.

If you need more informations, do not hesitate!

Patrick.

**Comment by AaronSadlerUK** [comment]
There is a typo in the documentation, use `v2cfturnstile` instead of `v2cfturnstyle` in the configuration

**Comment by roylaprattep** [comment]
Working!

 

Thank you very much.

 






 <https://twitter.com/roylaprattep>  <https://facebook.com/proylapratte/>  <https://linkedin.com/in/roylaprattep/>  <https://m.me/proylapratte> 


Patrick Roy Lapratte



Administrateur réseau et système | Expert Linux



@

***@***.*** ***@***.***> 


T

819.860.0222

**Comment by roylaprattep** [comment]
Working, thank you.
